"""initial schema

Revision ID: 7682c570084c
Revises:
Create Date: 2026-10-07 13:19:01.049627
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7682c570084c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_usage',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('endpoint', sa.String(length=500), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_time_ms', sa.Float(), nullable=True),
    sa.Column('request_size_bytes', sa.Integer(), nullable=True),
    sa.Column('response_size_bytes', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_api_usage_endpoint', 'api_usage', ['endpoint'], unique=False)
    op.create_index(op.f('ix_api_usage_id'), 'api_usage', ['id'], unique=False)
    op.create_index('ix_api_usage_user_id', 'api_usage', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('role', sa.Enum('patient', 'doctor', 'admin', name='user_role_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('preferred_language', sa.String(length=10), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('medical_registration_number', sa.String(length=100), nullable=True),
    sa.Column('specialization', sa.String(length=100), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index('ix_users_is_active', 'users', ['is_active'], unique=False)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('http_method', sa.String(length=10), nullable=True),
    sa.Column('endpoint', sa.String(length=500), nullable=True),
    sa.Column('http_status_code', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_event_type', 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index('ix_audit_logs_resource_type', 'audit_logs', ['resource_type'], unique=False)
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('token_hash', sa.String(length=512), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('device_name', sa.String(length=200), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index('ix_refresh_tokens_token_hash', 'refresh_tokens', ['token_hash'], unique=False)
    op.create_index('ix_refresh_tokens_user_id', 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('reports',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('report_type', sa.String(length=100), nullable=True),
    sa.Column('hospital_name', sa.String(length=255), nullable=True),
    sa.Column('doctor_name', sa.String(length=255), nullable=True),
    sa.Column('report_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('patient_age', sa.Integer(), nullable=True),
    sa.Column('patient_gender', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('pipeline_stage', sa.String(length=50), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('simplified_text', sa.Text(), nullable=True),
    sa.Column('simplified_text_hindi', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('ai_metadata', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reports_created_at', 'reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_index('ix_reports_status', 'reports', ['status'], unique=False)
    op.create_index('ix_reports_user_id', 'reports', ['user_id'], unique=False)
    op.create_table('abnormalities',
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('parameter_name', sa.String(length=255), nullable=False),
    sa.Column('parameter_unit', sa.String(length=50), nullable=True),
    sa.Column('detected_value', sa.String(length=100), nullable=False),
    sa.Column('numeric_value', sa.Float(), nullable=True),
    sa.Column('reference_range_low', sa.Float(), nullable=True),
    sa.Column('reference_range_high', sa.Float(), nullable=True),
    sa.Column('reference_range_text', sa.String(length=200), nullable=True),
    sa.Column('abnormality_type', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('clinical_significance', sa.Text(), nullable=True),
    sa.Column('plain_language_explanation', sa.Text(), nullable=True),
    sa.Column('is_llm_validated', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_abnormalities_id'), 'abnormalities', ['id'], unique=False)
    op.create_index('ix_abnormalities_report_id', 'abnormalities', ['report_id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('context_window_size', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_id'), 'chat_sessions', ['id'], unique=False)
    op.create_index('ix_chat_sessions_report_id', 'chat_sessions', ['report_id'], unique=False)
    op.create_index('ix_chat_sessions_user_id', 'chat_sessions', ['user_id'], unique=False)
    op.create_table('diagnoses',
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('condition_name', sa.String(length=255), nullable=False),
    sa.Column('icd10_code', sa.String(length=20), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('plain_language', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnoses_id'), 'diagnoses', ['id'], unique=False)
    op.create_index('ix_diagnoses_report_id', 'diagnoses', ['report_id'], unique=False)
    op.create_table('extracted_texts',
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('file_id', sa.String(length=36), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('cleaned_text', sa.Text(), nullable=True),
    sa.Column('ocr_provider', sa.String(length=50), nullable=False),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('language_detected', sa.String(length=10), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_texts_id'), 'extracted_texts', ['id'], unique=False)
    op.create_index('ix_extracted_texts_report_id', 'extracted_texts', ['report_id'], unique=False)
    op.create_table('lab_results',
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('test_name', sa.String(length=255), nullable=False),
    sa.Column('test_code', sa.String(length=50), nullable=True),
    sa.Column('result_value', sa.String(length=100), nullable=False),
    sa.Column('numeric_value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('reference_range', sa.String(length=200), nullable=True),
    sa.Column('is_abnormal', sa.Boolean(), nullable=False),
    sa.Column('abnormality_direction', sa.String(length=10), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_results_id'), 'lab_results', ['id'], unique=False)
    op.create_index('ix_lab_results_report_id', 'lab_results', ['report_id'], unique=False)
    op.create_table('medicines',
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('medicine_name', sa.String(length=255), nullable=False),
    sa.Column('generic_name', sa.String(length=255), nullable=True),
    sa.Column('dosage', sa.String(length=100), nullable=True),
    sa.Column('frequency', sa.String(length=100), nullable=True),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('route', sa.String(length=50), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('plain_language', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicines_id'), 'medicines', ['id'], unique=False)
    op.create_index('ix_medicines_report_id', 'medicines', ['report_id'], unique=False)
    op.create_table('report_chunks',
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('chunk_size', sa.Integer(), nullable=False),
    sa.Column('faiss_vector_id', sa.Integer(), nullable=True),
    sa.Column('embedding_model', sa.String(length=200), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_report_chunks_chunk_index', 'report_chunks', ['chunk_index'], unique=False)
    op.create_index(op.f('ix_report_chunks_id'), 'report_chunks', ['id'], unique=False)
    op.create_index('ix_report_chunks_report_id', 'report_chunks', ['report_id'], unique=False)
    op.create_table('report_files',
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('stored_filename', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_url', sa.String(length=1000), nullable=True),
    sa.Column('file_type', sa.String(length=10), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('checksum_md5', sa.String(length=32), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_files_id'), 'report_files', ['id'], unique=False)
    op.create_index('ix_report_files_report_id', 'report_files', ['report_id'], unique=False)
    op.create_table('report_versions',
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('snapshot_data', sa.JSON(), nullable=False),
    sa.Column('changed_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('change_reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_versions_id'), 'report_versions', ['id'], unique=False)
    op.create_index('ix_report_versions_report_id', 'report_versions', ['report_id'], unique=False)
    op.create_table('translations',
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('language_name', sa.String(length=50), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=False),
    sa.Column('translation_provider', sa.String(length=50), nullable=False),
    sa.Column('character_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translations_id'), 'translations', ['id'], unique=False)
    op.create_index('ix_translations_language_code', 'translations', ['language_code'], unique=False)
    op.create_index('ix_translations_report_id', 'translations', ['report_id'], unique=False)
    op.create_table('voice_requests',
    sa.Column('report_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('tts_provider', sa.String(length=50), nullable=False),
    sa.Column('audio_file_path', sa.String(length=1000), nullable=True),
    sa.Column('audio_file_url', sa.String(length=1000), nullable=True),
    sa.Column('audio_duration_seconds', sa.Float(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_requests_id'), 'voice_requests', ['id'], unique=False)
    op.create_index('ix_voice_requests_report_id', 'voice_requests', ['report_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_chunks', sa.JSON(), nullable=True),
    sa.Column('retrieved_context', sa.Text(), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('is_helpful', sa.Boolean(), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_messages_created_at', 'chat_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_index('ix_chat_messages_session_id', 'chat_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chat_messages_session_id', table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_index('ix_chat_messages_created_at', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('ix_voice_requests_report_id', table_name='voice_requests')
    op.drop_index(op.f('ix_voice_requests_id'), table_name='voice_requests')
    op.drop_table('voice_requests')
    op.drop_index('ix_translations_report_id', table_name='translations')
    op.drop_index('ix_translations_language_code', table_name='translations')
    op.drop_index(op.f('ix_translations_id'), table_name='translations')
    op.drop_table('translations')
    op.drop_index('ix_report_versions_report_id', table_name='report_versions')
    op.drop_index(op.f('ix_report_versions_id'), table_name='report_versions')
    op.drop_table('report_versions')
    op.drop_index('ix_report_files_report_id', table_name='report_files')
    op.drop_index(op.f('ix_report_files_id'), table_name='report_files')
    op.drop_table('report_files')
    op.drop_index('ix_report_chunks_report_id', table_name='report_chunks')
    op.drop_index(op.f('ix_report_chunks_id'), table_name='report_chunks')
    op.drop_index('ix_report_chunks_chunk_index', table_name='report_chunks')
    op.drop_table('report_chunks')
    op.drop_index('ix_medicines_report_id', table_name='medicines')
    op.drop_index(op.f('ix_medicines_id'), table_name='medicines')
    op.drop_table('medicines')
    op.drop_index('ix_lab_results_report_id', table_name='lab_results')
    op.drop_index(op.f('ix_lab_results_id'), table_name='lab_results')
    op.drop_table('lab_results')
    op.drop_index('ix_extracted_texts_report_id', table_name='extracted_texts')
    op.drop_index(op.f('ix_extracted_texts_id'), table_name='extracted_texts')
    op.drop_table('extracted_texts')
    op.drop_index('ix_diagnoses_report_id', table_name='diagnoses')
    op.drop_index(op.f('ix_diagnoses_id'), table_name='diagnoses')
    op.drop_table('diagnoses')
    op.drop_index('ix_chat_sessions_user_id', table_name='chat_sessions')
    op.drop_index('ix_chat_sessions_report_id', table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index('ix_abnormalities_report_id', table_name='abnormalities')
    op.drop_index(op.f('ix_abnormalities_id'), table_name='abnormalities')
    op.drop_table('abnormalities')
    op.drop_index('ix_reports_user_id', table_name='reports')
    op.drop_index('ix_reports_status', table_name='reports')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_index('ix_reports_created_at', table_name='reports')
    op.drop_table('reports')
    op.drop_index('ix_refresh_tokens_user_id', table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_token_hash', table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_audit_logs_user_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_resource_type', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_event_type', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index('ix_users_is_active', table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_api_usage_user_id', table_name='api_usage')
    op.drop_index(op.f('ix_api_usage_id'), table_name='api_usage')
    op.drop_index('ix_api_usage_endpoint', table_name='api_usage')
    op.drop_table('api_usage')
    # ### end Alembic commands ###
